### ISSUE TITLE
Media Loading Error Display / Text

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#11]
Some changes to make the errors displayed more useful/clear/readable:

## 1. Add a background box that is similar the one used on the Splash Screen
- Same Transparent White Background
- Rounded Corners
- Black Text

Currently the white text is not readable on top of white slides.

## 2. Update the Error Text
- Error describes the "media" that did not load
- Error provides help for students

### image-audio
The audio for this Storybook Page could not be loaded. Please try refreshing your browser. Contact support if you continue to have issues.
**Expected audio:** assets/pages/slide17.mp3

The image for this Storybook Page could not be loaded. Please try refreshing your browser. Contact support if you continue to have issues.
**Expected image:** assets/pages/slide17.svg

The audio and image for this Storybook Page could not be loaded. Please try refreshing your browser. Contact support if you continue to have issues.
**Expected audio:** assets/pages/slide17.mp3
**Expected image:** assets/pages/slide17.svg

### Video
The video for this Storybook Page could not be loaded. Please try refreshing your browser. Contact support if you continue to have issues.
**Expected video:** assets/pages/slide17.mp4

---

I understand what the intent of the original error was, but we have to recognize these errors will occur for end users too. We can figure out what's going on while developing, and don't need to be told that our file format is wrong.

I also understand that you might not have anything in place to differentiate between audio and images. Please look into adding that functionality. It would go a long way to making sure a student knows that the error displaying is not intact an error in-itself. They might link "oh, I see the slide, the error must be wrong… and it's in the way of the slide text!" When in fact they should know the audio that goes on that Storybook Page is not loaded.

Remember how Crystal didn't understand the Table of Contents? We are thinking of users like that.

**Comment by Lin87** [comment]
Are you referring to error messages in the VideoJS area?

**Comment by owlboy** [comment]
Yes.

<img width="927" alt="screen shot 2016-08-09 at 2 56 35 pm" src="https://cloud.githubusercontent.com/assets/237349/17531450/8785b1e6-5e41-11e6-939d-aa7440032168.png">
<img width="909" alt="screen shot 2016-08-09 at 2 56 32 pm" src="https://cloud.githubusercontent.com/assets/237349/17531449/8780e01c-5e41-11e6-94df-3fe442a5ed3a.png">

**Comment by Lin87** [comment]
Some of the error messages are internal to VideoJS core script. I will look into what I can do about it. The appearances can definitely be modified.

**Comment by Lin87** [comment]
Updated!
![screen shot 2016-08-12 at 2 41 46 pm](https://cloud.githubusercontent.com/assets/2531526/17635046/0725584c-609b-11e6-881d-9254865992e8.png)

**Comment by owlboy** [comment]
Sadly, it looks like this might be acting a bit odd. This demo here throws an error, but incorrectly says the slide image is missing.

• Project is configured as image-audio, and no audio exists.
• Error says the image is missing.

https://media.uwex.edu/content/ds/ds740/ds740_lesson1_presentation3-temp-for-ethan

![screen shot 2016-08-12 at 4 55 53 pm](https://cloud.githubusercontent.com/assets/237349/17638127/a97f8f6a-60ad-11e6-9d35-65a5a37be876.png)

I'm leaving that presentation as-is ready for you until this ticket is re-closed.

**Comment by Lin87** [comment]
D'oh! The condition statement is correct. Just the string is wrong. Copy and paste fail...

**Comment by owlboy** [comment]
Similarly, Kaltura video errors render incorrectly also:

![screen shot 2016-08-19 at 5 37 36 pm](https://cloud.githubusercontent.com/assets/237349/17826170/b87eb9ba-6633-11e6-87d8-054cd3ccf894.png)


Double check YouTube and Vimeo too.

**Comment by owlboy** [comment]
While I'm at it, can we get the "Expected X:" text to be bold please, for easier skimmability.

**Comment by owlboy** [comment]
Another case to test and accommodate for, Slide bundles.

**Comment by Lin87** [comment]
Fixed and also added error message for bundled images
