### ISSUE TITLE
Quizes - Multiple Choice Multiple Answer - Feedback Heading/Label is Displayed

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#12]
When a <multipleChoiceMultiple> quiz question is answered, it shows a blank Feedback section.

As we don't support feedback on multiple answer questions, this should not happen. It will seem like a rendering error to users.

![screen shot 2016-08-19 at 5 33 08 pm](https://cloud.githubusercontent.com/assets/237349/17826091/1206156a-6633-11e6-864b-a974d9b3537c.png)

**Comment by Lin87** [comment]
Actually we do. Feedback is supported for multiple answers questions. It's setup like short answer question.

**Comment by owlboy** [comment]
Oh, I'll have to update my Storybook Template then. Right now it does not ask for some.

New Ticket Incoming.
