### ISSUE TITLE
Quiz - Question Formatting - Indents

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#14]
To make things cleaner, and easer to read, we need to have the Radio buttons and Checkboxes of quiz question answers be separate and to the left of the blocks of text that are associated with them.

**Current Appearance:**
<img width="752" alt="screen shot 2016-08-26 at 4 02 15 pm" src="https://cloud.githubusercontent.com/assets/237349/18020330/818a2a70-6ba6-11e6-9790-008f7cdaa0da.png">

**Mockup of Requested Appearance:**
<img width="750" alt="screen shot 2016-08-26 at 4 00 03 pm" src="https://cloud.githubusercontent.com/assets/237349/18020338/865acd70-6ba6-11e6-9ef1-a8a23b4775e1.png">

**Comment by Lin87** [comment]
done
