### ISSUE TITLE
Quiz - Short Answer - Audio Support

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#15]
It seems we support audio and images on all question types now. But it looks like Short Answer might have been overlooked for the Audio part.

Specifically, audio as part of the question.

**Example Presentation:**
https://media.uwex.edu/content/ds/ds760/ds760_lesson1-utilitarianism/

There is a Quiz on Storybook page 06 that should have audio associated with the question.

**Comment by Lin87** [comment]
Actually I didn't program short answer to have audio support. I don't think it make sense to have an audio for short answer question and instructors bother to create audio for short answer question. Also, short answer response is check for correctness at all.

**Comment by owlboy** [comment]
Well, then I guess this has changed to a feature request. Leave it to a philosophy instructor to decide it would be useful.

**Comment by Lin87** [comment]
Is this still urgent?

**Comment by owlboy** [comment]
Yes

**Comment by Lin87** [comment]
done
