### ISSUE TITLE
Author Profile - Show What is Available to Show

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#16]
When loading the author profile, it would be preferable to have it load what it does have instead of completely failing. 

This is in addition to continuing to attempt to fallback to centralized assets once it knows local versions of the Author Photo and Author Profile don't exist. Including supporting a mix/match of all possibilities. (Local Profile & Central Picture; Central Profile & Local Picture; Local Picture, Completely Missing Profile; etc.)

**Comment by Lin87** [comment]
Hi Bryan -

Did you sent me a place holder for author photo incase both local and central pictures do not exist? I don't remember. The past few weeks had been a blur ... and a few thought suppression. If you did not, would you like me to create one? Not sure if you are already working on it.

Thanks!

**Comment by Lin87** [comment]
Done! Ignore my previous comment.
