### ISSUE TITLE
Author Profile - Error Reporting

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#17]
Please update the Author Profile loading errors to be more granular and clearly communicated.

**Report when a JSON file exists, but it failed to read in properly (Syntax errors in the JSON):**
* **Message:** "Author profile failed to load. Syntax error."
* **Formatting:** Plain text, red. (As it is now)

**Report when an author profile is missing:** 
* **Message:** "Author profile not available."
* **Formatting:** Bold, black, same size as the author name. (Same formatting as the author name) – We do not want this to be red because a missing profile might be _intentional_ expected behavior for that presentation.

**When the author photo is missing, please make Storybook do the following:**

* Make the Photo background exactly twice the height of the "Author Profile" heading bar above it.
* Load the included profile icon centered in the space (Both vertically and Horizontally)

**Mockup:**
![profile_photo-missing](https://cloud.githubusercontent.com/assets/237349/18148591/2950749c-6fa0-11e6-8b4e-f9cb4d6f6274.png)

**The Profile Icon:**
 [profile_photo.svg.zip](https://github.com/oel-mediateam/sbplus_v3/files/448420/profile_photo.svg.zip)

This icon is from Icomoon, it's "0501 user" and I have colored it `#656b70`, please use that color.

**Comment by Lin87** [comment]
Done!
