### ISSUE TITLE
Author Profile - Center Heading Vertically

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#18]
Please center the Author Profile heading text vertically in the bar. Currently it changes depending on the size of the viewport. The larger the size, the more uncentered it gets.

![screen shot 2016-08-31 at 5 55 51 pm](https://cloud.githubusercontent.com/assets/237349/18149158/44ab6b30-6fa4-11e6-8312-70ad99f59a01.png)

**Comment by Lin87** [comment]
When you have time, could you test this? I am not able to test this because I have a UltraWide 21:9 monitor.

**Comment by owlboy** [comment]
It appears to be working! Thank you.

**Example:** https://youtu.be/5XpdGt-wbWw
