### ISSUE TITLE
Downloads are Not being Found When They Exsist

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#2]
Here is the project we have found the issue with:

https://media.uwex.edu/content/smgt/smgt115_r16/smgt115_lesson1a/

It looks like Storybook is searching for an incorrect filename string.

![screen shot 2016-07-13 at 10 57 38 am](https://cloud.githubusercontent.com/assets/237349/16810196/b088513e-48e8-11e6-8a9e-2680c46fa39e.png)

**Comment by Lin87** [comment]
Oops. Fixed. I called the get program directory instead of get root directory function.
