### ISSUE TITLE
Math - Impliment MathJax

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#20]
So, this is the ultimate solution to getting Math working once and for all in a consistent way in Storybook. We probally should have implimented it last year, but I was working hard trying to avoid loading another Javascript library every time a Storybook presentation is used.

So, I feel we should impliment MathJax in the current version of Storybook v3.

If you feel loading this library for every presentation would be a bad practice, then I would request that we do it in a way so it can load optionally based on a sbplus.xml tag.

Something like `<storybook mathjax="yes">`

https://www.mathjax.org/

**Comment by Lin87** [comment]
Done!
