### ISSUE TITLE
Kaltura Videos - Handle Videos that are Processing in a more Understandable Way

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#26]
When a video on Kaltura has been recently uploaded, it exhibits some weird behavior in Storybook until it is done processing.

Two examples of it behaving weirdly:
- Displaying an error saying that the audio for that Storybook Page could not be found, and then saying the expected audio file is the Kaltura ID.
- Say we have a 4 Page presentation. Page one has a fully functioning Kaltura video. The next three are still processing. If I view Page 1, and then Page 2, 3, and 4, they all display the video from Page 1, no indication it could not load the intended video, no errors. Just a functioning page playing the wrong video. This is confusing for people who don't understand Kaltura and how it processes videos. It could lead a project creator to think their XML is wrong. But if they check their XML they will find it is correct. So they try again and it's still showing the wrong video. Minutes later, from their point of view, it just "magically" starts working. They don't know or care about the processing necessarily.

There is another situation where I struggle with this, even though I fully understand the reasons behind the weirdness. That situation occurs when I send one of these presentations to ID. I tell them videos are still processing. But they _still_ sometimes report to me that the pages that are processing are broken, or displaying the wrong content. My response sadly up until now is some messaged version of "yeah, it's acting weird because of that processing I mentioned…"

I feel strongly that the solution is _not_: Tell people that while a Kaltura video is still processing that Storybook will act erratically.

The solution is to support this situation properly with proper error messages. I am assuming the Kaltura API returns a code/message when a video is still processing. This needs to be caught and used to display the more useful message, and end the confusing erratic behavior.

Also, I totally understand why this was not considered before now. You never encountered such a situation when creating the Kaltura feature. Test videos were always all finished and ready to play.

When you are ready to tackle this, I can help you with the Kaltura side of making the "still processing" situations.

**Comment by Lin87** [comment]
This is completed a weeks ago and live alread.
