### ISSUE TITLE
Invalid XML Error - Minor Convenience update

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#27]
Hello!

Minor update request:

When you have an incorrect XML file, you helpfully link to where I could get it validated to sort out the issue. Lets take this a step further by making it load the XML in question too!

So, all we need to do is replace the link to the validator site with one with a query string for the URL to the sbplus.xml file of the presentation.

**Original:**
`Validate the XML at <a href="https://validator.w3.org/">https://validator.w3.org/</a>.`

**Proposed Change:**
`<a href="https://validator.w3.org/check?uri=$$SBPLUS.XML$$&charset=%28detect+automatically%29&doctype=Inline&group=0">Validate the XML at the WC3 Markup Validation Service</a>`
(**$$SBPLUS.XML$$** is where the URL to the sbplus.xml of the project goes)

All other text and formatting choices that are currently on the page are great.

**Comment by Lin87** [comment]
This is completed and included in version 3.1.0.
