### ISSUE TITLE
Splash fails to Load when a Course SVG is in Place

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#3]
Right now when I put the /smgt/115.svg in place it causes projects for SMGT115 to stop loading/initializing.

**Example Project:**
https://media.uwex.edu/content/smgt/smgt115_r16/smgt115_lesson1a/

`<setup course="115">`

The information and start / download buttons fail to load. But if I remove the 115.svg it loads again, with the default splash.

**Comment by Lin87** [comment]
fixed.
