### ISSUE TITLE
Notes Formatting - Minor issue with Lists

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#37]
Hello,

I just put a list in a note and noticed that lines following the first line are not indented to be aligned with the first.

![screen shot 2016-11-17 at 12 36 40 pm](https://cloud.githubusercontent.com/assets/237349/20402555/bf014872-acc2-11e6-96b8-5fdc2c683dee.png)

**Comment by Lin87** [comment]
Fixed in version 3.1.
