### ISSUE TITLE
Instructor Profile is Failing to Load

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#4]
The instructor profile is blank in this presentation, but I think everything is in place and configured in the XML correctly. I might be wrong.

**Example Presentation:**
https://media.uwex.edu/content/smgt/smgt115_r16/smgt115_lesson20b/

Eric Sanden
ericsanden.jpg
ericsanden.json

**Comment by Lin87** [comment]
Text in the XML override the server file.
