### ISSUE TITLE
Images Jump / Scale During Page Change When in Zoomed Mode

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#49]
Hello,

I am working on a presentation that will be used at the Faculty Symposium and we plan to present using Storybook in Zoomed mode in a Fullscreen Browser. 

Transitions seem fast without flicker or loading spinners. But when in zoomed mode they jump around as they are scaled to fit into the content area.

**Example:** https://youtu.be/yDdjYd51jH0
**Presentation:** [faculty_symposium_2017-infomercial](https://media.uwex.edu/content/faculty/faculty_symposium_2017/faculty_symposium_2017-infomercial/)

If this could be fixed it would be fantastic. The jumps are very distracting/Ugly as they are now, especially for a presentation to a crowd of Faculty.

The Symposium is on Monday May 22nd. So we have time, but if this could be tweaked as soon as possible that would be fantastic.

Thank you!

**Comment by Lin87** [comment]
Would version 3.1 solves the issue? [Presentation with version 3.1](https://media.uwex.edu/sandbox/ethan/sbplus_3_1/faculty_symposium_2017/index.html). Version 3.1 can go into full/zoom view as well.

**Comment by owlboy** [comment]
No, because we are using it completely full screen. something 3.1 does not do. Unless you have a way to make 3.1 do that.
