### ISSUE TITLE
Playback at .5x is causing reverberation

### ISSUE THREAD

**Issue by patrick-wirth** [oel-mediateam/sbplus_v3#5]
Hi Ethan,

When I play back audio and video at .5x, there is an echo.  It's jarring when you hear it the first time. 

I'm using Firefox 46.0.1

Thanks,
Patrick

**Comment by Lin87** [comment]
That is normal. Slower speed pick up sounds that you usually don't pick up.

**Comment by owlboy** [comment]
Yeah, it's funky but expected performance.
