### ISSUE TITLE
Should We Display a Single Tab when there is Only one?

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#59]
_I would like input on this issue from @Lin87 @patrick-wirth @mwolfensteinuwex._

It was brought up at a meeting that maybe we should consider hiding the tab when only one Note or Widget is being displayed.

**In Support of Hiding the Single Tab:**
• Allows for the space to be used for content
• If it's just one tab, and there is no possibility of more appearing dynamically, there is no reason for it to be there.
• We never labeled the notes section "Notes" before now
• They are useful mainly for differentiation between Notes and Widgets

**In Support of Displaying the Single Tab:**
• It is visually consistent with other slides with notes/widgets
• It labels the Notes / Widget (But this could be done via text inside of the note / widget)
• It's simpler to implement on Ethan's end

**Comment by Lin87** [comment]
I had it hidden before when there is only one tab/segment. But I don't remember the reason why I removed. It was mentioned in heuristic evaluation.

Ethan Lin
ethan.lin@uwex.edu

**Comment by Lin87** [comment]
I think I remembered the reason why I removed it. The reason was what if there is no notes but has one widget. It's not notes, but users does not know that. So, it was displayed for labeling purposes. I have no strong objection to hiding it, and I can easily turn it back on/off.

**Comment by Lin87** [comment]
@owlboy @patrick-wirth We can address/discuss this issue in our upcoming SB+ meetings next week. @mwolfensteinuwex would you be interested in attending the meeting? You don't have to if you are busy.

**Comment by mwolfensteinuwex** [comment]
As long as I'm available on my calendar I'm happy to attend.
