### ISSUE TITLE
Captions are Not Displaying

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#6]
Captions are not displaying.

**Example Project:**
https://media.uwex.edu/content/himt/himt300_r16/himt300_unit1/

If Matt resizes the viewport, he can manage to make it appear. It seems like it is displaying both too low, and on a layer/z-depth that is below the slide image. Or it is just too low and under the notes div.

Here is a video of that:
https://youtu.be/LrX87aMqNVU

In Safari I don't have captions, but can't make the graphical artifact/error happen. Matt can make it happen in Chrome and Firefox. (I think Safari is just good at keeping the rendering up-to-date and clean.)

**Comment by Lin87** [comment]
Fixed. No, it just that I had the z-index on the video poster image set too high for the caption to appear on top.
