### ISSUE TITLE
Update Labels

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#63]
To make what settings do more clear to end users, please make the following updates:

## In Settings

**General**
- Hide Notes/Widgets area by default
- Hide Table of Contents by default
- Disable Interactive Transcript (alpha)

**Video and Audio Player**
- Autoplay audio and video
- Default Volume Level (%)
- Default playback rate
- Always display subtitles

## Elsewhere
- Update "Hide Widget" button to be "Toggle Notes/Widgets Area"

**Comment by Lin87** [comment]
Label updated
