### ISSUE TITLE
Formatting Issue - Lists in Quizzes

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#66]
There is an issue with rendering lists in Quizzes. Bullets and numbers in lists get cut off on the left because the indentation of the list items is removed.

**Screenshot:**
<img width="677" alt="screen shot 2017-06-20 at 3 12 15 pm" src="https://user-images.githubusercontent.com/237349/27353802-ffaebc72-55ca-11e7-9c68-02280927d657.png">

**Example Presentation (Storybook Page 09):**
https://media.uwex.edu/content/apc/apc310/apc310_lesson1/

**Comment by Lin87** [comment]
Fixed. Many of the pages are mission audio/mp3. I assumed that is on purpose.
