### ISSUE TITLE
Author Profile Photo Formatting

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#7]
Hello,

This is something we discussed at one point, and I just wanted to get it in a formal ticket so it's not lost in the shuffle and so you can get to it when you have time.

The author profile photo needs some formatting set so that it can be a higher resolution image ready for high DPI screens, and not get gigantic.

I have attached an example screenshot that is at about the standard embed size of 900x630.

**The specifications / Requirements:**
* Max height of 300px
* Grey background gets wider to fill in empty space as the viewport gets bigger
* Grey background does not get taller
* Photo is centered in the grey background
* Photo can be any aspect ratio, a really wide photo would be cutoff on the sides at smaller viewport sizes. A super tall photo would scale to fit it's full height in the fixed height photo area, leaving a large amount of grey background showing.

**Standard Viewport/iFrame Embed:**
![profile_photo](https://cloud.githubusercontent.com/assets/237349/17307019/a045956a-57f8-11e6-8780-d5b584824b90.jpg)

**Huge Viewport:**
![profile_photo-huge-viewport](https://cloud.githubusercontent.com/assets/237349/17307121/24a18dbe-57f9-11e6-89f6-2879234cad5f.jpg)

Let me know if you have more questions!

**Comment by Lin87** [comment]
Formatted author image to as shown in the pictures above.
