### ISSUE TITLE
Author Profile Picture Display Assumes Dimensions 

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#71]
Hello,

Here is an edge case where the profile picture is wider than it is tall. The issue is just having too much space below, and showing the placeholder underneath. The width of the image is fine. It's expected that I would need to fit in the width standard images would use.

*Example Presentation:*
https://media.uwex.edu/content/ds/ds775/ds775_week5/

**Comment by Lin87** [comment]
issue resolved by removing the min-height property in CSS.
