### ISSUE TITLE
Feature Request: preventAutoPlay="yes" Flag

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#73]
Hello,

Nick came to Ethan and I today with a feature request for Storybook that would add a flag to pages that would prevent them from autoplaying when arriving at the page.

The use case he has in mind is a mostly silent text commentary presentation that ends with a video. He would like students to be able to control when the video starts as to not be surprised by audio in the video after spending awhile in silence.

I think that adding a optional `preventAutoPlay="yes"` flag to the `<page>` tag would be ideal for this. And the flag title would make it very clear what it is for. The intent would be for it to work on all slide types that use the built in VideoJS player. And we would work to make sure it is not confusable with a feature that autoplays the whole presentation page after page.

**Comment by Lin87** [comment]
I have this request posted on SB+ v3.2 idea board in DaPulse. We will discussed it (and others) when we are ready to move forward with v3.2.

**Comment by Lin87** [comment]
Completed in version 3.2
