### ISSUE TITLE
Tweak: Load Default Splash Screen _After_ Others Fail

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#77]
Hello,

Minor tweak that will enhance the fit and finish of Storybook.

Please make it so that when the presentation initially loads it attempts to load the custom splash screens before loading the default one. Currently depending on your connection the default blue one can come up easily, sometimes flashing for just a moment before the actual one fades in. This is distracting and can read as an error.

Thanks!

**Comment by Lin87** [comment]
Fixed in commit https://github.com/oel-mediateam/sbplus_v3/commit/6c72be37a67e84610088cd6176694692da748a58
