### ISSUE TITLE
Error Messages are Not Displaying

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#78]
I am currently not having error messages appear when slide images or audio are missing. Additionally, the status of a kaltura video is not displaying when it is uploading/processing/not ready.

**Comment by Lin87** [comment]
Fixed in commit https://github.com/oel-mediateam/sbplus_v3/commit/294ef8f9b232774fa1a96da6006bfae522381979

**Comment by owlboy** [comment]
When an image and audio are missing, the audio error currently overwrites the image error.

**Comment by Lin87** [comment]
Done. 
<img width="470" alt="error screen" src="https://user-images.githubusercontent.com/2531526/36326711-b0fb10b6-1321-11e8-958c-9e075415b0a3.png">. Update will be available shortly.
