### ISSUE TITLE
Update The Outer Border to use an Alpha Channel So That it Shows as a Dark Line on all Backgrounds

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#82]
Something like Black with 25% alpha. Whatever makes it appear the current grey on white.

This is to avoid having it being bright white on darker colors.

**Comment by Lin87** [comment]
Updated in commit https://github.com/oel-mediateam/sbplus_v3/commit/0541d075e4e2f35a0c600140e0adde7eaba0cfee
