### ISSUE TITLE
Hide Placeholder Profile Pic When a Picture is Loaded

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#83]
It should be replaced or hidden so that it does not appear underneath uniquely shaped images such as this example:

![screen shot 2018-07-27 at 11 53 53 am](https://user-images.githubusercontent.com/237349/43334926-06b47a42-9194-11e8-905c-60c3c88284b9.png)

https://media.uwex.edu/content/ds/ds705_r17/ds705_lesson9-part2/

**Comment by Lin87** [comment]
Should be fixed. Please double check and close if everything is good.

**Comment by owlboy** [comment]
Looks good!
