### ISSUE TITLE
Ordered List in Quiz Item is not Displaying Numbers

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#85]
The ordered list in the question of a quiz item is not displaying numbers:
Seen in Safari.
**Example (Storybook Page 14):**
https://media.uwex.edu/content/apc/apc400/apc400_lesson1/

**Screenshot:**
![screen shot 2018-08-08 at 2 10 12 pm](https://user-images.githubusercontent.com/237349/43858892-d4987632-9b14-11e8-8336-82d6b8d6e200.png)

**Comment by Lin87** [comment]
It was never intended to have a list in quiz question. I can add it.

**Comment by Lin87** [comment]
Should be updated in commit https://github.com/oel-mediateam/sbplus_v3/commit/80cf28bd2fd074511b6d2210eae342759bdb9745.
