### ISSUE TITLE
Explore/Implement an official XML Schema for Storybook

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#89]
This would allow validators to know how to treat the XML document, and define the spec for anyone looking at the format. It would also allow validators to offer error/warning messages for incomplete or broken Storybook specific XML tags/attributes.

**Comment by Lin87** [comment]
After half-day of research, I don't think this is possible with the validator at https://validator.w3.org/. It always displayed the `Schema Error: Cannot find preset schema for namespace...`error message. I even tested an XML file created by W3C and got the same error message. Plus, this W3C validator complains when the XML character encoding is not US-ASCII (basic English, no accent characters, etc.)

I created the schema for the sbplus.xml, https://media.uwex.edu/app/storybook_plus_v3/sbplus.xsd. I tested this schema and sbplus.xml files with other XML validators (https://www.freeformatter.com/xml-validator-xsd.html, http://www.utilities-online.info/xsdvalidation/, etc.), and they all worked.

My conclusion is that W3C validator no longer works (or outdated) for XML validation. The error message is a bug that W3C no longer bother to fix.

**Comment by Lin87** [comment]
Add the following attributes to test against the schema:
`<storybook ... xmlns="https://media.uwex.edu/app/storybook_plus_v3/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://media.uwex.edu/app/storybook_plus_v3/ https://media.uwex.edu/app/storybook_plus_v3/sbplus.xsd">`

**Comment by Lin87** [comment]
XML error message screen updated with a new message. Three XML validator services are listed as alternatives. All of them can validate XML by URL, upload, or direct input. W3C validator link removed as it is no longer validate XML.
