### ISSUE TITLE
Notes Section Stops Rendering When you Return to It

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#90]
Hello,

In Safari, Chrome, and Firefox I am having an issue where if I navigate to a Storybook Page with notes, it renders the notes the first time. If I navigate away and then return it does not render the notes area and instead renders the placeholder logo.

**Example Presentation (Page 6 has Notes):**
[APC440 - Module 3](https://media.uwex.edu/content/apc/apc440/apc440_module3/)

**Comment by Lin87** [comment]
Fixed. Will be in the next update.
