### ISSUE TITLE
Presentations made by the Packager do not Properly Display Downloadable Assets

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#92]
If a project is made with the packager and uses .sbproj it does not intelligently find the supporting downloadable assets like the transcript once on the web server.

**Comment by owlboy** [comment]
**Example Project:**
https://media.uwex.edu/content/apc/apc430/apc430_lesson10.sbproj

**Comment by Lin87** [comment]
Fixed and live.

**Comment by owlboy** [comment]
Thanks!
