### ISSUE TITLE
Work around an issue with SVGs not rendering inline raster images in Safari

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#95]
Ethan and I discussed an issue where SVG images fail to render inline raster images upon initial rendering. When they are rendered a second time they always render.

The proposed workaround is to render them once discretely out of sight, and then render them a second time for presentation to the user. The StackOverflow item below appears to suggest a different work-around.

A good test presentation:
https://media.uwex.edu/showcases/biological-anthropology/

The StackOverflow item that I originally found when first noticing this issue:
https://stackoverflow.com/questions/20609997/svg-with-image-inside-is-not-showing-in-safari

**Comment by Lin87** [comment]
This enhancement is live. Currently, it is preloading all types of images. However, it will only discretely render SVG image to the DOM. Please confirm.

**Comment by owlboy** [comment]
I'll need some extra time to assess this fix, I'll let you know when I can!

**Comment by owlboy** [comment]
Actually, looks like it is not helping yet.

**Comment by Lin87** [comment]
Please schedule a meeting with me or grab me whenever you are free. I am going to be out of the office tomorrow (Friday) and next week Tuesday tru the rest of the week (8/27-9/3).
