### ISSUE TITLE
Update Kaltura videos to load the default thumbnail from Kaltura

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#97]
Currently, it appears that when a video is loaded but not autoplay, it displays the video paused on the first frame while waiting to play.

This is confusing for producers who would like to customize what frame is being displayed while paused. - Please update the video player to display Kaltura thumbnails when paused because autoplay is off.

**Comment by Lin87** [comment]
Kaltura video should now display the thumbnail from Kaltura if autoplay is turned off. The fix is live. Please confirm.

**Comment by owlboy** [comment]
This is working 👍
